spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loto
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
