spring:
  datasource:
    url: jdbc:h2:mem:loto
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
