spring:
  application:
    name: loto
  profiles:
    group:
      test: 
        - h2
        - local
        - api
      dev:
        - mysql
        - local
        - api
      prod:
        - prod
    active: dev
