spring:
  logging:
    level:
      root: debug
      org.springframework: debug
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.SQL: debug
    org.zaxxer.hikari: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace